feat: add new plugin type for cache manager
gravitee-io/graviteeio-node pull request #211
Opened 2023-04-19 12:43 UTC by guillaumelamirand

**Issue**

https://gravitee.atlassian.net/browse/ARCHI-231

**Description**

Following the work done on cluster, now make cache manager as plugin.

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `3.1.0-archi-231-cache-manager-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/3.1.0-archi-231-cache-manager-SNAPSHOT/gravitee-node-3.1.0-archi-231-cache-manager-SNAPSHOT.zip)

2023-04-19 14:39 UTC, remibaptistegio requested changes

2023-04-19 14:47 UTC, guillaumelamirand commented on gravitee-node-cache/gravitee-node-cache-common/src/main/java/io/gravitee/node/plugin/cache/common/InMemoryCache.java
> +                        case SIZE:
I can move this and handle it the same way I do with expired, wdyt?

2023-04-19 14:50 UTC, guillaumelamirand commented on gravitee-node-cache/gravitee-node-cache-plugin-standalone/pom.xml
> +        <caffeine.version>2.5.5</caffeine.version>
no more yes!

2023-04-19 14:53 UTC, guillaumelamirand commented on gravitee-node-cache/gravitee-node-cache-common/src/main/java/io/gravitee/node/plugin/cache/common/InMemoryCache.java
> +                        case SIZE:
Ok I just use  onEntryEvicted

2023-04-19 15:08 UTC, remibaptistegio approved these changes

2023-04-19 15:09 UTC, merged

2023-07-17 12:33 UTC, graviteeio commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- `4.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-05-07 12:40 UTC, graviteeio commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: